# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63ced7a4c95e525b417304d639ab9639660fe58c11e61e72552f71228118b11f42f10866bb4bf68861b24e47787032608e8709edcdad4c515451833fd18ce615

test:
  secret_key_base: 48c6f58979eb84a0c3096f68491fc3069a3a72f57aadd205c575d7f99b338c290c2a855a688d914f4409de0f9062ea2d5b2912ff93502463b066f8c4cbc00fce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
